baseURL = 'https://projects.enchantedcode.co.uk'
languageCode = 'en'
title = 'Enchanted Code - Projects'
theme = "hugo-geekdoc"

pluralizeListTitles = false

pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true
enableRobotsTXT = true

[params]
geekdocLogo = "favicon.svg"
geekdocRepo = "https://github.com/enchant97/projects"
geekdocEditPath = "edit/main"
geekdocDarkModeDim = false
geekdocCollapseAllSections = true

[params.geekdocContentLicense]
    name = "CC BY-NC-ND 4.0"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"
